### ISSUE TITLE
Doc update to URN format and usage

### ISSUE THREAD

**Issue by m1small** [pulumi/pulumi-cloudflare#310]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Update docs to emphasize use of single quotes in the URN.
Confusion led to lost productivity.

### Affected area/feature

If run without Quotes, for example: ```pulumi state delete URN -s STACK ```
Leads to confusing behavior such as: "* error finding Cloudflare API Token" and "error: No such resource".

**Comment by susanev** [comment]
what docs? can you link to the docs you are talking about?
im not sure this has anything to do with cloudflare

**Comment by squaremo** [comment]
The docs for `pulumi state delete` do recommend using single quotes to avoid shell expansion: https://www.pulumi.com/docs/reference/cli/pulumi_state_delete/#pulumi-state-delete
Presumably the problem is with pulumi-cloudflare API docs, but I can't find it with [a search](https://github.com/search?q=repo%3Apulumi%2Fpulumi-cloudflare%20%22pulumi%20state%20delete%22&type=code) -- @m1small would you link to the offending advice, please.

**Comment by m1small** [comment]
Thanks for pointing this out, and I agree.   After re-triaging, I'm closing this issue.  Thanks!
